///*
// * To change this license header, choose License Headers in Project Properties.
// * To change this template file, choose Tools | Templates
// * and open the template in the editor.
// */
//package com.gvidia.gvidia.ui.systemadminworkarea;
//
//import com.gvidia.gvidia.business.EcoSystem;
//import com.gvidia.gvidia.business.enterprises.retailer.personnel.customer.Customer;
//import com.gvidia.gvidia.business.deliveryman.DeliveryMan;
//
//import javax.swing.JPanel;
//
//import com.gvidia.gvidia.ui.Colors;
//import com.gvidia.gvidia.ui.base.Controller;//import com.gvidia.gvidia.ui.panels.LoginPanel;
//import com.gvidia.gvidia.ui.panels.tables.ActionInterface;
//import com.gvidia.gvidia.ui.panels.tables.DisplayTable;
//import com.gvidia.gvidia.ui.panels.tables.ElementButton;
//import java.util.Arrays;
//
/**
 *
 * @author Krishica
 */
//public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {
//
//    /**
//     * Creates new form SystemAdminWorkAreaJPanel
//     */
//    Controller mController;
//    EcoSystem ecosystem;
//    public SystemAdminWorkAreaJPanel(Controller cont,EcoSystem ecosystem) {
//        System.out.println(getClass().getResource("/images/logout.png"));
//        initComponents();
//        this.mController=cont;
//        this.ecosystem=ecosystem;
//        loadPanels();
//
//        btn_1MousePressed(null);
//    }
//
//    public void changeWorkContainerPanel(JPanel panel) {
//        System.out.println("Panel Changed: "+panel);
//        jSplitPane1.setRightComponent(panel);
//    }
//
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
//    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
//    private void initComponents() {
//
//        jSplitPane1 = new javax.swing.JSplitPane();
//        jPanel1 = new javax.swing.JPanel();
//        side_pane = new javax.swing.JPanel();
//        logout_btn = new javax.swing.JPanel();
//        ind_logout = new javax.swing.JPanel();
//        jLabel10 = new javax.swing.JLabel();
//        jLabel3 = new javax.swing.JLabel();
//        btn_1 = new javax.swing.JPanel();
//        ind_1 = new javax.swing.JPanel();
//        jLabel8 = new javax.swing.JLabel();
//        jLabel1 = new javax.swing.JLabel();
//        btn_2 = new javax.swing.JPanel();
//        ind_2 = new javax.swing.JPanel();
//        jLabel9 = new javax.swing.JLabel();
//        jLabel2 = new javax.swing.JLabel();
//        btn_3 = new javax.swing.JPanel();
//        ind_3 = new javax.swing.JPanel();
//        jLabel11 = new javax.swing.JLabel();
//        jLabel4 = new javax.swing.JLabel();
//        imageAvatar1 = new com.gvidia.gvidia.ui.panels.ImageAvatar();
//        workContainerPanel = new javax.swing.JPanel();
//
//        setMaximumSize(new java.awt.Dimension(800, 600));
//        setMinimumSize(new java.awt.Dimension(800, 600));
//        setPreferredSize(new java.awt.Dimension(800, 600));
//        setLayout(new java.awt.BorderLayout());
//
//        jSplitPane1.setDividerLocation(150);
//        jSplitPane1.setDividerSize(0);
//        jSplitPane1.setLastDividerLocation(150);
//        jSplitPane1.setMaximumSize(new java.awt.Dimension(800, 600));
//        jSplitPane1.setMinimumSize(new java.awt.Dimension(800, 600));
//        jSplitPane1.setPreferredSize(new java.awt.Dimension(800, 600));
//
//        jPanel1.setMaximumSize(new java.awt.Dimension(150, 800));
//        jPanel1.setMinimumSize(new java.awt.Dimension(150, 800));
//        jPanel1.setPreferredSize(new java.awt.Dimension(150, 800));
//        jPanel1.setRequestFocusEnabled(false);
//
//        side_pane.setBackground(Colors.DARK);
//        side_pane.setMaximumSize(new java.awt.Dimension(150, 800));
//        side_pane.setMinimumSize(new java.awt.Dimension(150, 800));
//        side_pane.setPreferredSize(new java.awt.Dimension(150, 800));
//        side_pane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
//
//        logout_btn.setBackground(Colors.DARK
//        );
//        logout_btn.addMouseListener(new java.awt.event.MouseAdapter() {
//            public void mousePressed(java.awt.event.MouseEvent evt) {
//                logout_btnMousePressed(evt);
//            }
//        });
//
//        ind_logout.setOpaque(false);
//        ind_logout.setPreferredSize(new java.awt.Dimension(3, 43));
//
//        javax.swing.GroupLayout ind_logoutLayout = new javax.swing.GroupLayout(ind_logout);
//        ind_logout.setLayout(ind_logoutLayout);
//        ind_logoutLayout.setHorizontalGroup(
//            ind_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGap(0, 3, Short.MAX_VALUE)
//        );
//        ind_logoutLayout.setVerticalGroup(
//            ind_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGap(0, 43, Short.MAX_VALUE)
//        );
//
//        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
//        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
//        jLabel10.setText("Logout");
//
//        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nisha\\Documents\\Studies\\Fall 2021\\INFO5100\\Assignment 5\\JuberEats\\src\\main\\resources\\images\\logout.png")); // NOI18N
//        jLabel3.setLabelFor(logout_btn);
//        jLabel3.setText("jLabel1");
//
//        javax.swing.GroupLayout logout_btnLayout = new javax.swing.GroupLayout(logout_btn);
//        logout_btn.setLayout(logout_btnLayout);
//        logout_btnLayout.setHorizontalGroup(
//            logout_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(logout_btnLayout.createSequentialGroup()
//                .addComponent(ind_logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(18, 18, 18)
//                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(18, 18, Short.MAX_VALUE)
//                .addComponent(jLabel10)
//                .addGap(44, 44, 44))
//        );
//        logout_btnLayout.setVerticalGroup(
//            logout_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(logout_btnLayout.createSequentialGroup()
//                .addComponent(ind_logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(0, 0, Short.MAX_VALUE))
//            .addGroup(logout_btnLayout.createSequentialGroup()
//                .addContainerGap()
//                .addGroup(logout_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addGroup(logout_btnLayout.createSequentialGroup()
//                        .addGap(2, 2, 2)
//                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//                .addContainerGap())
//        );
//
//        side_pane.add(logout_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, -1, -1));
//
//        btn_1.setBackground(Colors.DARK
//        );
//        btn_1.addMouseListener(new java.awt.event.MouseAdapter() {
//            public void mousePressed(java.awt.event.MouseEvent evt) {
//                btn_1MousePressed(evt);
//            }
//        });
//
//        ind_1.setOpaque(false);
//        ind_1.setPreferredSize(new java.awt.Dimension(3, 43));
//
//        javax.swing.GroupLayout ind_1Layout = new javax.swing.GroupLayout(ind_1);
//        ind_1.setLayout(ind_1Layout);
//        ind_1Layout.setHorizontalGroup(
//            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGap(0, 3, Short.MAX_VALUE)
//        );
//        ind_1Layout.setVerticalGroup(
//            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGap(0, 43, Short.MAX_VALUE)
//        );
//
//        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
//        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
//        jLabel8.setText("Cusomters");
//
//        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nisha\\Documents\\Studies\\Fall 2021\\INFO5100\\Assignment 5\\JuberEats\\src\\main\\resources\\images\\customer.png")); // NOI18N
//        jLabel1.setLabelFor(btn_1);
//        jLabel1.setText("jLabel1");
//
//        javax.swing.GroupLayout btn_1Layout = new javax.swing.GroupLayout(btn_1);
//        btn_1.setLayout(btn_1Layout);
//        btn_1Layout.setHorizontalGroup(
//            btn_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(btn_1Layout.createSequentialGroup()
//                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(18, 18, 18)
//                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(18, 18, Short.MAX_VALUE)
//                .addComponent(jLabel8)
//                .addGap(44, 44, 44))
//        );
//        btn_1Layout.setVerticalGroup(
//            btn_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(btn_1Layout.createSequentialGroup()
//                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(0, 0, Short.MAX_VALUE))
//            .addGroup(btn_1Layout.createSequentialGroup()
//                .addContainerGap()
//                .addGroup(btn_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addGroup(btn_1Layout.createSequentialGroup()
//                        .addGap(2, 2, 2)
//                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//                .addContainerGap())
//        );
//
//        side_pane.add(btn_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 150, -1));
//
//        btn_2.setBackground(Colors.DARK
//        );
//        btn_2.addMouseListener(new java.awt.event.MouseAdapter() {
//            public void mousePressed(java.awt.event.MouseEvent evt) {
//                btn_2MousePressed(evt);
//            }
//        });
//
//        ind_2.setOpaque(false);
//        ind_2.setPreferredSize(new java.awt.Dimension(3, 43));
//
//        javax.swing.GroupLayout ind_2Layout = new javax.swing.GroupLayout(ind_2);
//        ind_2.setLayout(ind_2Layout);
//        ind_2Layout.setHorizontalGroup(
//            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGap(0, 3, Short.MAX_VALUE)
//        );
//        ind_2Layout.setVerticalGroup(
//            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGap(0, 43, Short.MAX_VALUE)
//        );
//
//        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
//        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
//        jLabel9.setText("Delivery Men");
//
//        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nisha\\Documents\\Studies\\Fall 2021\\INFO5100\\Assignment 5\\JuberEats\\src\\main\\resources\\images\\deliver.png")); // NOI18N
//        jLabel2.setLabelFor(btn_2);
//        jLabel2.setText("jLabel1");
//
//        javax.swing.GroupLayout btn_2Layout = new javax.swing.GroupLayout(btn_2);
//        btn_2.setLayout(btn_2Layout);
//        btn_2Layout.setHorizontalGroup(
//            btn_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(btn_2Layout.createSequentialGroup()
//                .addComponent(ind_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(18, 18, 18)
//                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(18, 18, Short.MAX_VALUE)
//                .addComponent(jLabel9)
//                .addGap(44, 44, 44))
//        );
//        btn_2Layout.setVerticalGroup(
//            btn_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(btn_2Layout.createSequentialGroup()
//                .addContainerGap()
//                .addGroup(btn_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addGroup(btn_2Layout.createSequentialGroup()
//                        .addGap(2, 2, 2)
//                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//                .addGap(71, 71, 71))
//            .addGroup(btn_2Layout.createSequentialGroup()
//                .addComponent(ind_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(67, 67, 67))
//        );
//
//        side_pane.add(btn_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, 50));
//
//        btn_3.setBackground(Colors.DARK
//        );
//        btn_3.addMouseListener(new java.awt.event.MouseAdapter() {
//            public void mousePressed(java.awt.event.MouseEvent evt) {
//                btn_3MousePressed(evt);
//            }
//        });
//
//        ind_3.setOpaque(false);
//        ind_3.setPreferredSize(new java.awt.Dimension(3, 43));
//
//        javax.swing.GroupLayout ind_3Layout = new javax.swing.GroupLayout(ind_3);
//        ind_3.setLayout(ind_3Layout);
//        ind_3Layout.setHorizontalGroup(
//            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGap(0, 3, Short.MAX_VALUE)
//        );
//        ind_3Layout.setVerticalGroup(
//            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGap(0, 43, Short.MAX_VALUE)
//        );
//
//        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
//        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
//        jLabel11.setText("Restaurants");
//
//        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nisha\\Documents\\Studies\\Fall 2021\\INFO5100\\Assignment 5\\JuberEats\\src\\main\\resources\\images\\shop.png")); // NOI18N
//        jLabel4.setLabelFor(logout_btn);
//        jLabel4.setText("jLabel1");
//
//        javax.swing.GroupLayout btn_3Layout = new javax.swing.GroupLayout(btn_3);
//        btn_3.setLayout(btn_3Layout);
//        btn_3Layout.setHorizontalGroup(
//            btn_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(btn_3Layout.createSequentialGroup()
//                .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(18, 18, 18)
//                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(18, 18, Short.MAX_VALUE)
//                .addComponent(jLabel11)
//                .addGap(44, 44, 44))
//        );
//        btn_3Layout.setVerticalGroup(
//            btn_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(btn_3Layout.createSequentialGroup()
//                .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(0, 0, Short.MAX_VALUE))
//            .addGroup(btn_3Layout.createSequentialGroup()
//                .addContainerGap()
//                .addGroup(btn_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addGroup(btn_3Layout.createSequentialGroup()
//                        .addGap(2, 2, 2)
//                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//                .addContainerGap())
//        );
//
//        side_pane.add(btn_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, -1, -1));
//        side_pane.add(imageAvatar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 130));
//
//        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
//        jPanel1.setLayout(jPanel1Layout);
//        jPanel1Layout.setHorizontalGroup(
//            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(jPanel1Layout.createSequentialGroup()
//                .addComponent(side_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(0, 0, Short.MAX_VALUE))
//        );
//        jPanel1Layout.setVerticalGroup(
//            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(jPanel1Layout.createSequentialGroup()
//                .addComponent(side_pane, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(0, 196, Short.MAX_VALUE))
//        );
//
//        jSplitPane1.setLeftComponent(jPanel1);
//
//        workContainerPanel.setMaximumSize(new java.awt.Dimension(650, 600));
//        workContainerPanel.setMinimumSize(new java.awt.Dimension(650, 600));
//
//        javax.swing.GroupLayout workContainerPanelLayout = new javax.swing.GroupLayout(workContainerPanel);
//        workContainerPanel.setLayout(workContainerPanelLayout);
//        workContainerPanelLayout.setHorizontalGroup(
//            workContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGap(0, 650, Short.MAX_VALUE)
//        );
//        workContainerPanelLayout.setVerticalGroup(
//            workContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGap(0, 600, Short.MAX_VALUE)
//        );
//
//        jSplitPane1.setRightComponent(workContainerPanel);
//
//        add(jSplitPane1, java.awt.BorderLayout.CENTER);
//    }// </editor-fold>//GEN-END:initComponents
//
//    private void btn_1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_1MousePressed
//        // TODO add your handling code here:
//        setActive(btn_1, ind_1);
//        resetColor(new JPanel[]{btn_2,btn_3}, new JPanel[]{ind_2,ind_3});
//        loadPanels();
//        changeWorkContainerPanel(CustomerTable);
//
//    }//GEN-LAST:event_btn_1MousePressed
//
//    private void btn_2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_2MousePressed
//        // TODO add your handling code here:
//        setActive(btn_2, ind_2);
//        resetColor(new JPanel[]{btn_1,btn_3}, new JPanel[]{ind_1,ind_3});
//        loadPanels();
//        changeWorkContainerPanel(DeliveryManTable);
//
//    }//GEN-LAST:event_btn_2MousePressed
//
//    private void logout_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_btnMousePressed
//        // TODO add your handling code here:
//
//        mController.getmMainFrame().changePanel(new LoginPanel(mController));
//
//        setActive(logout_btn, ind_logout);
//        resetColor(new JPanel[]{btn_1,btn_3, btn_2}, new JPanel[]{ind_1,ind_3, ind_3});
//
//    }//GEN-LAST:event_logout_btnMousePressed
//
//    private void btn_3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_3MousePressed
//        // TODO add your handling code here:
//        setActive(btn_3, ind_3);
//        resetColor(new JPanel[]{btn_2,btn_1}, new JPanel[]{ind_2,ind_1});
//        loadPanels();
//        changeWorkContainerPanel(RestaurantTable);
//    }//GEN-LAST:event_btn_3MousePressed
//
//     private void setActive(JPanel pane, JPanel ind) {
//        pane.setBackground(Colors.PRIMARY );
//        ind.setOpaque(true);
//
//    }
//
//    private void resetColor(JPanel [] pane, JPanel [] indicators)
//    {
//        for(int i=0;i<pane.length;i++){
//           pane[i].setBackground(Colors.DARK);
//
//        } for(int i=0;i<indicators.length;i++){
//           indicators[i].setOpaque(false);
//        }
//
//    }
//
//    // Variables declaration - do not modify//GEN-BEGIN:variables
//    private javax.swing.JPanel btn_1;
//    private javax.swing.JPanel btn_2;
//    private javax.swing.JPanel btn_3;
//    private com.gvidia.gvidia.ui.panels.ImageAvatar imageAvatar1;
//    private javax.swing.JPanel ind_1;
//    private javax.swing.JPanel ind_2;
//    private javax.swing.JPanel ind_3;
//    private javax.swing.JPanel ind_logout;
//    private javax.swing.JLabel jLabel1;
//    private javax.swing.JLabel jLabel10;
//    private javax.swing.JLabel jLabel11;
//    private javax.swing.JLabel jLabel2;
//    private javax.swing.JLabel jLabel3;
//    private javax.swing.JLabel jLabel4;
//    private javax.swing.JLabel jLabel8;
//    private javax.swing.JLabel jLabel9;
//    private javax.swing.JPanel jPanel1;
//    private javax.swing.JSplitPane jSplitPane1;
//    private javax.swing.JPanel logout_btn;
//    private javax.swing.JPanel side_pane;
//    private javax.swing.JPanel workContainerPanel;
//    // End of variables declaration//GEN-END:variables
//
//    public DisplayTable CustomerTable;
//    public DisplayTable DeliveryManTable;
//    public DisplayTable RestaurantTable;
//
//
//
//
//    public void loadPanels(){
//
//
//        CustomerTable =  new DisplayTable<Customer>(
//            ecosystem.getCustomerDirectory().getList(),
//                "Customers",
//                 Arrays.asList(
//                new ElementButton<Customer>("Create", "create.png", new ActionInterface<Customer>() {
//                    @Override
//                    public void action(Customer t) {
//                        changeWorkContainerPanel(new CustomerInfoPanel(null, true));
//                    }
//                }),
//                new ElementButton<Customer>("Edit", "edit.png", new ActionInterface<Customer>() {
//                    @Override
//                    public void action(Customer t) {
//                        changeWorkContainerPanel(new CustomerInfoPanel(t, false));
//                    }
//                }),
//                new ElementButton<Customer>("Delete", "delete.png", new ActionInterface<Customer>() {
//                    @Override
//                    public void action(Customer c) {
//                         c.delete();
//                         ecosystem.getDeliveryManDirectory().delete(c.getmID());
//                    }
//                })
//              )
//        );
//
//        DeliveryManTable = new DisplayTable<DeliveryMan>(
//            ecosystem.getDeliveryManDirectory().getList(),
//                "DeliveryMan",
//            Arrays.asList(
//                new ElementButton<DeliveryMan>("Create", "create.png", new ActionInterface<DeliveryMan>() {
//            @Override
//            public void action(DeliveryMan C) {
//                changeWorkContainerPanel(new DeliveryManPanel(true,null));
//
//            }}),
//                new ElementButton<DeliveryMan>("Edit", "edit.png", new ActionInterface<DeliveryMan>() {
//            @Override
//            public void action(DeliveryMan c) {
//                 changeWorkContainerPanel(new DeliveryManPanel(false,c));
//
//            }}),
//                new ElementButton<DeliveryMan>("Delete", "delete.png", new ActionInterface<DeliveryMan>() {
//            @Override
//            public void action(DeliveryMan c) {
//                  c.delete();
//                    ecosystem.getDeliveryManDirectory().delete(c.getmID());
//
//            }})
//            )
//        );
//
//        RestaurantTable = new DisplayTable<Restaurant>(
//            ecosystem.getRestaurantDirectory().getList(),
//                "Restaurants",
//            Arrays.asList(new ElementButton<Restaurant>("Create", "create.png", new ActionInterface<Restaurant>() {
//            @Override
//            public void action(Restaurant t) {
//                    changeWorkContainerPanel(new RestarauntInfoPanel(null,true));
//            }
//                }),
//                new ElementButton<Restaurant>("Edit", "edit.png", new ActionInterface<Restaurant>() {
//            @Override
//            public void action(Restaurant t) {
//                    changeWorkContainerPanel(new RestarauntInfoPanel(t,false));
//            }
//                }),
//                new ElementButton<>("Delete", "delete.png", new ActionInterface<Restaurant>() {
//            @Override
//            public void action(Restaurant r) {
//                     r.delete();
//                    ecosystem.getRestaurantDirectory().delete(r.getmID());
//                    RestaurantTable.setUptable();
//
//            }
//                })
//            )
//        );
//
//
//
//
//    }
//
//
//}
