/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gvidia.gvidia.ui.panels;

import com.gvidia.gvidia.business.EcoSystem;
import com.gvidia.gvidia.business.enterprise.Enterprise;
import com.gvidia.gvidia.business.enterprise.organisation.Organization;
import com.gvidia.gvidia.business.useraccount.UserAccount;
import com.gvidia.gvidia.business.utils.ImageUtil;
import com.gvidia.gvidia.business.utils.Validators;
import com.gvidia.gvidia.ui.Colors;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import com.gvidia.gvidia.ui.base.Controller;
import com.gvidia.gvidia.ui.base.MainJFrame;

/**
 *
 * @author Nisha
 */
public class LoginPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginPanel
     */


    Controller mController;
    EcoSystem system;
    Colors color;
    public LoginPanel(Controller mController) {
        color = Colors.getSysAdminColors();
        initComponents();
        BufferedImage img = null;
        this.mController = mController;


        try {
            img = ImageIO.read(new File("logo.png"));
        } catch (IOException e) {
            e.printStackTrace();
        }
        Image dimg = img.getScaledInstance(750, 450,
                Image.SCALE_SMOOTH);
        ImageIcon imageIcon = new ImageIcon(dimg);
        jLabel1.setIcon(imageIcon);
        
        jLabel3.setIcon(ImageUtil.getImageIcon(450, 350, ImageUtil.BASE_IMAGE + "home.jpg"));
        

        system = mController.getmEcoSystem();

    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cnfrmPassTxtField = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usernameTxtField = new javax.swing.JTextField();

        setBackground(color.BACKGROUND);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel1.setText("jLabel1");

        cnfrmPassTxtField.setBackground(Colors.BACKGROUND);
        cnfrmPassTxtField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cnfrmPassTxtField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, color.PRIMARY_DARK()));
        cnfrmPassTxtField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cnfrmPassTxtField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        cnfrmPassTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnfrmPassTxtFieldActionPerformed(evt);
            }
        });

        jLabel2.setBackground(color.PRIMARY()
        );
        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setForeground(color.PRIMARY_DARK());
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Login");
        jLabel2.setBorder(new javax.swing.border.LineBorder(color.PRIMARY(), 2, true));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });

        jLabel9.setBackground(color.SECONDARY_DARK());
        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel9.setForeground(color.PRIMARY_DARK());
        jLabel9.setText("Password");

        jLabel8.setBackground(color.SECONDARY_DARK());
        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel8.setForeground(color.PRIMARY_DARK());
        jLabel8.setText("Username");

        jLabel3.setMaximumSize(new java.awt.Dimension(350, 350));
        jLabel3.setMinimumSize(new java.awt.Dimension(350, 350));
        jLabel3.setPreferredSize(new java.awt.Dimension(350, 350));

        usernameTxtField.setBackground(Colors.BACKGROUND);
        usernameTxtField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        usernameTxtField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, color.PRIMARY_DARK()));
        usernameTxtField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        usernameTxtField.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cnfrmPassTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(26, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usernameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cnfrmPassTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(205, 205, 205))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cnfrmPassTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnfrmPassTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnfrmPassTxtFieldActionPerformed

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        // TODO add your handling code here:

        String userName = usernameTxtField.getText();
        String password = new String(cnfrmPassTxtField.getPassword());
        JOptionPane.showConfirmDialog(this, password);
        if(!Validators.isAlphaNum(password)) {
           JOptionPane.showMessageDialog(this, "Password is not valid");
           return;
        }
        if(!Validators.isAlphaNum(userName)) {
           JOptionPane.showMessageDialog(this, "UserName is not valid");
           return;
        }
       UserAccount userAccount = system.getUserAccountDirectory().authenticateUser(userName, password);
        if(userAccount == null) {
            JOptionPane.showMessageDialog(mController.getmMainFrame(), "User not found");
            return;
        }
        Enterprise ent = system.getEnterprise(userAccount.getRole());
        Organization org = ent != null ? 
                ent.getOrganisation(userAccount.getRole()) : null;
        System.out.println(userAccount.getRole());
        mController.getmMainFrame().changePanel(
                userAccount.getRole().createWorkArea(
                        mController, org, userAccount, ent));

        
    }//GEN-LAST:event_jLabel2MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField cnfrmPassTxtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField usernameTxtField;
    // End of variables declaration//GEN-END:variables
}
