//
//
//package com.gvidia.gvidia.ui.deliverymanrole;
//
//
//import com.gvidia.gvidia.business.EcoSystem;
//import com.gvidia.gvidia.business.deliveryman.DeliveryMan;
//import com.gvidia.gvidia.business.order.OrderWorkRequest;
//import com.gvidia.gvidia.business.useraccount.UserAccount;
//import javax.swing.JPanel;
//import com.gvidia.gvidia.ui.Colors;
//import com.gvidia.gvidia.ui.base.Controller;//import com.gvidia.gvidia.ui.panels.LoginPanel;
//import com.gvidia.gvidia.ui.panels.personnelPanels.DeliveryManPanel;
//import com.gvidia.gvidia.ui.panels.tables.ActionInterface;
//import com.gvidia.gvidia.ui.panels.tables.DisplayTable;
//import com.gvidia.gvidia.ui.panels.tables.ElementButton;
//import java.util.Arrays;
//import javax.swing.JOptionPane;
//
/**
 *
 * @author Krishica
 */
//public class DeliveryManAreaJPanel extends javax.swing.JPanel {
//
//    Controller mController;
//    EcoSystem ecosystem;
//    DeliveryMan mDeliveryMan;
//    UserAccount mAccount;
//
//    /** Creates new form AdminWorkAreaJPanel */
//    public DeliveryManAreaJPanel( Controller cunt, UserAccount acc) {
//        initComponents();
//        this.mController = cunt;
//        ecosystem = EcoSystem.getInstance(true);
//        mAccount = acc;
//        mDeliveryMan = (DeliveryMan) mAccount.getRole().getmObjective();
//
//        //valueLabel.setText();
//        btn_2MousePressed(null);
//    }
//
//    public void changeWorkContainerPanel(JPanel panel) {
//        System.out.println("Panel Changed: "+panel);
//        jSplitPane1.setRightComponent(panel);
//    }
//
//    /** This method is called from within the constructor to
//     * initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is
//     * always regenerated by the Form Editor.
//     */
//    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
//    private void initComponents() {
//
//        jSplitPane1 = new javax.swing.JSplitPane();
//        jPanel1 = new javax.swing.JPanel();
//        side_pane = new javax.swing.JPanel();
//        logout_btn = new javax.swing.JPanel();
//        ind_logout = new javax.swing.JPanel();
//        jLabel10 = new javax.swing.JLabel();
//        jLabel3 = new javax.swing.JLabel();
//        btn_2 = new javax.swing.JPanel();
//        ind_2 = new javax.swing.JPanel();
//        jLabel9 = new javax.swing.JLabel();
//        jLabel2 = new javax.swing.JLabel();
//        btn_4 = new javax.swing.JPanel();
//        ind_4 = new javax.swing.JPanel();
//        jLabel12 = new javax.swing.JLabel();
//        jLabel5 = new javax.swing.JLabel();
//        workContainerPanel = new javax.swing.JPanel();
//
//        setMaximumSize(new java.awt.Dimension(800, 600));
//        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
//
//        jSplitPane1.setDividerLocation(150);
//        jSplitPane1.setDividerSize(0);
//        jSplitPane1.setLastDividerLocation(150);
//        jSplitPane1.setMaximumSize(new java.awt.Dimension(800, 600));
//        jSplitPane1.setMinimumSize(new java.awt.Dimension(800, 600));
//        jSplitPane1.setPreferredSize(new java.awt.Dimension(800, 600));
//
//        jPanel1.setMaximumSize(new java.awt.Dimension(150, 800));
//        jPanel1.setMinimumSize(new java.awt.Dimension(150, 800));
//        jPanel1.setRequestFocusEnabled(false);
//
//        side_pane.setBackground(Colors.DARK);
//        side_pane.setMaximumSize(new java.awt.Dimension(150, 800));
//        side_pane.setMinimumSize(new java.awt.Dimension(150, 800));
//        side_pane.setPreferredSize(new java.awt.Dimension(150, 800));
//        side_pane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
//
//        logout_btn.setBackground(Colors.DARK
//        );
//        logout_btn.addMouseListener(new java.awt.event.MouseAdapter() {
//            public void mousePressed(java.awt.event.MouseEvent evt) {
//                logout_btnMousePressed(evt);
//            }
//        });
//
//        ind_logout.setOpaque(false);
//        ind_logout.setPreferredSize(new java.awt.Dimension(3, 43));
//
//        javax.swing.GroupLayout ind_logoutLayout = new javax.swing.GroupLayout(ind_logout);
//        ind_logout.setLayout(ind_logoutLayout);
//        ind_logoutLayout.setHorizontalGroup(
//            ind_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGap(0, 3, Short.MAX_VALUE)
//        );
//        ind_logoutLayout.setVerticalGroup(
//            ind_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGap(0, 43, Short.MAX_VALUE)
//        );
//
//        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
//        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
//        jLabel10.setText("Logout");
//
//        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nisha\\Documents\\Studies\\Fall 2021\\INFO5100\\Assignment 5\\JuberEats\\src\\main\\resources\\images\\logout.png")); // NOI18N
//        jLabel3.setText("jLabel1");
//
//        javax.swing.GroupLayout logout_btnLayout = new javax.swing.GroupLayout(logout_btn);
//        logout_btn.setLayout(logout_btnLayout);
//        logout_btnLayout.setHorizontalGroup(
//            logout_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(logout_btnLayout.createSequentialGroup()
//                .addComponent(ind_logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(18, 18, 18)
//                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(18, 18, Short.MAX_VALUE)
//                .addComponent(jLabel10)
//                .addGap(44, 44, 44))
//        );
//        logout_btnLayout.setVerticalGroup(
//            logout_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(logout_btnLayout.createSequentialGroup()
//                .addComponent(ind_logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(0, 0, Short.MAX_VALUE))
//            .addGroup(logout_btnLayout.createSequentialGroup()
//                .addContainerGap()
//                .addGroup(logout_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addGroup(logout_btnLayout.createSequentialGroup()
//                        .addGap(2, 2, 2)
//                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//                .addContainerGap())
//        );
//
//        side_pane.add(logout_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, -1, -1));
//
//        btn_2.setBackground(Colors.DARK
//        );
//        btn_2.addMouseListener(new java.awt.event.MouseAdapter() {
//            public void mousePressed(java.awt.event.MouseEvent evt) {
//                btn_2MousePressed(evt);
//            }
//        });
//
//        ind_2.setOpaque(false);
//        ind_2.setPreferredSize(new java.awt.Dimension(3, 43));
//
//        javax.swing.GroupLayout ind_2Layout = new javax.swing.GroupLayout(ind_2);
//        ind_2.setLayout(ind_2Layout);
//        ind_2Layout.setHorizontalGroup(
//            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGap(0, 3, Short.MAX_VALUE)
//        );
//        ind_2Layout.setVerticalGroup(
//            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGap(0, 43, Short.MAX_VALUE)
//        );
//
//        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
//        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
//        jLabel9.setText("Orders");
//
//        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nisha\\Documents\\Studies\\Fall 2021\\INFO5100\\Assignment 5\\JuberEats\\src\\main\\resources\\images\\book.png")); // NOI18N
//        jLabel2.setText("jLabel1");
//
//        javax.swing.GroupLayout btn_2Layout = new javax.swing.GroupLayout(btn_2);
//        btn_2.setLayout(btn_2Layout);
//        btn_2Layout.setHorizontalGroup(
//            btn_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(btn_2Layout.createSequentialGroup()
//                .addComponent(ind_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(18, 18, 18)
//                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(18, 18, Short.MAX_VALUE)
//                .addComponent(jLabel9)
//                .addGap(44, 44, 44))
//        );
//        btn_2Layout.setVerticalGroup(
//            btn_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(btn_2Layout.createSequentialGroup()
//                .addContainerGap()
//                .addGroup(btn_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addGroup(btn_2Layout.createSequentialGroup()
//                        .addGap(2, 2, 2)
//                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//                .addGap(71, 71, 71))
//            .addGroup(btn_2Layout.createSequentialGroup()
//                .addComponent(ind_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(67, 67, 67))
//        );
//
//        side_pane.add(btn_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, 50));
//
//        btn_4.setBackground(Colors.DARK
//        );
//        btn_4.addMouseListener(new java.awt.event.MouseAdapter() {
//            public void mousePressed(java.awt.event.MouseEvent evt) {
//                btn_4MousePressed(evt);
//            }
//        });
//
//        ind_4.setOpaque(false);
//        ind_4.setPreferredSize(new java.awt.Dimension(3, 43));
//
//        javax.swing.GroupLayout ind_4Layout = new javax.swing.GroupLayout(ind_4);
//        ind_4.setLayout(ind_4Layout);
//        ind_4Layout.setHorizontalGroup(
//            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGap(0, 3, Short.MAX_VALUE)
//        );
//        ind_4Layout.setVerticalGroup(
//            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGap(0, 43, Short.MAX_VALUE)
//        );
//
//        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
//        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
//        jLabel12.setText("Edit Info");
//
//        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nisha\\Documents\\Studies\\Fall 2021\\INFO5100\\Assignment 5\\JuberEats\\src\\main\\resources\\images\\customer.png")); // NOI18N
//        jLabel5.setText("jLabel1");
//
//        javax.swing.GroupLayout btn_4Layout = new javax.swing.GroupLayout(btn_4);
//        btn_4.setLayout(btn_4Layout);
//        btn_4Layout.setHorizontalGroup(
//            btn_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(btn_4Layout.createSequentialGroup()
//                .addComponent(ind_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(18, 18, 18)
//                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(18, 18, Short.MAX_VALUE)
//                .addComponent(jLabel12)
//                .addGap(53, 53, 53))
//        );
//        btn_4Layout.setVerticalGroup(
//            btn_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(btn_4Layout.createSequentialGroup()
//                .addComponent(ind_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(0, 0, Short.MAX_VALUE))
//            .addGroup(btn_4Layout.createSequentialGroup()
//                .addContainerGap()
//                .addGroup(btn_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addGroup(btn_4Layout.createSequentialGroup()
//                        .addGap(2, 2, 2)
//                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//                .addContainerGap())
//        );
//
//        side_pane.add(btn_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 140, -1));
//
//        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
//        jPanel1.setLayout(jPanel1Layout);
//        jPanel1Layout.setHorizontalGroup(
//            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(jPanel1Layout.createSequentialGroup()
//                .addComponent(side_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(0, 0, Short.MAX_VALUE))
//        );
//        jPanel1Layout.setVerticalGroup(
//            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(jPanel1Layout.createSequentialGroup()
//                .addComponent(side_pane, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(0, 107, Short.MAX_VALUE))
//        );
//
//        jSplitPane1.setLeftComponent(jPanel1);
//
//        workContainerPanel.setMaximumSize(new java.awt.Dimension(650, 600));
//        workContainerPanel.setMinimumSize(new java.awt.Dimension(650, 600));
//
//        javax.swing.GroupLayout workContainerPanelLayout = new javax.swing.GroupLayout(workContainerPanel);
//        workContainerPanel.setLayout(workContainerPanelLayout);
//        workContainerPanelLayout.setHorizontalGroup(
//            workContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGap(0, 650, Short.MAX_VALUE)
//        );
//        workContainerPanelLayout.setVerticalGroup(
//            workContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGap(0, 600, Short.MAX_VALUE)
//        );
//
//        jSplitPane1.setRightComponent(workContainerPanel);
//
//        add(jSplitPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
//    }// </editor-fold>//GEN-END:initComponents
//
//    private void logout_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_btnMousePressed
//        // TODO add your handling code here:
//        setActive(logout_btn, logout_btn);
//        mController.getmMainFrame().changePanel(new LoginPanel(mController));
//    }//GEN-LAST:event_logout_btnMousePressed
//
//    private void btn_2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_2MousePressed
//        // TODO add your handling code here:
//        setActive(btn_2, ind_2);
//        ind_2.setOpaque(true);
//        resetColor(new JPanel[]{btn_4}, new JPanel[]{ind_4});
//        loadPanels();
//        changeWorkContainerPanel(DeliveryTable);
//
//    }//GEN-LAST:event_btn_2MousePressed
//
//    private void btn_4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_4MousePressed
//        // TODO add your handling code here:
//         setActive(btn_4, ind_4);
//        resetColor(new JPanel[]{btn_2}, new JPanel[]{ind_2});
//
//        loadPanels();
//        changeWorkContainerPanel(new DeliveryManPanel(false,mDeliveryMan));
//
//
//    }//GEN-LAST:event_btn_4MousePressed
//
//     private void setActive(JPanel pane, JPanel ind) {
//        pane.setBackground(Colors.PRIMARY );
//        ind.setOpaque(true);
//    }
//
//    private void resetColor(JPanel [] pane, JPanel [] indicators)
//    {
//        for(int i=0;i<pane.length;i++){
//           pane[i].setBackground(Colors.DARK);
//
//        } for(int i=0;i<indicators.length;i++){
//           indicators[i].setOpaque(false);
//        }
//
//    }
//
//
//    // Variables declaration - do not modify//GEN-BEGIN:variables
//    private javax.swing.JPanel btn_2;
//    private javax.swing.JPanel btn_4;
//    private javax.swing.JPanel ind_2;
//    private javax.swing.JPanel ind_4;
//    private javax.swing.JPanel ind_logout;
//    private javax.swing.JLabel jLabel10;
//    private javax.swing.JLabel jLabel12;
//    private javax.swing.JLabel jLabel2;
//    private javax.swing.JLabel jLabel3;
//    private javax.swing.JLabel jLabel5;
//    private javax.swing.JLabel jLabel9;
//    private javax.swing.JPanel jPanel1;
//    private javax.swing.JSplitPane jSplitPane1;
//    private javax.swing.JPanel logout_btn;
//    private javax.swing.JPanel side_pane;
//    private javax.swing.JPanel workContainerPanel;
//    // End of variables declaration//GEN-END:variables
//
//
//    public DisplayTable DeliveryTable;
//
//
//
//    public void loadPanels(){
//
//        DeliveryTable = new DisplayTable<OrderWorkRequest>(
//            mDeliveryMan.getmDeliveryRequest().getList(),
//                "Deliveries",
//            Arrays.asList(null,
//                new ElementButton<>("Mark as Complete", "tick.png", new ActionInterface<OrderWorkRequest>() {
//            @Override
//            public void action(OrderWorkRequest r) {
//
//                   if(!r.getStatus().equalsIgnoreCase("En Route")) {
//                     JOptionPane.showMessageDialog(DeliveryManAreaJPanel.this, "Already Delivered");
//                     return;
//                   }
//
//
//                   r.setResolved();
//                   DeliveryTable.setUptable();
//                }
//             }),
//                new ElementButton<>("Deliver", "deliver.png", new ActionInterface<OrderWorkRequest>() {
//            @Override
//            public void action(OrderWorkRequest r) {
//
//                if(!r.getStatus().equalsIgnoreCase("Assigned")) {
//                    JOptionPane.showMessageDialog(DeliveryManAreaJPanel.this, "Already Assigned");
//                    return;
//                }
//                mDeliveryMan.mCurrentRequest = r;
//                r.getmOrder().setmDeliveryMan(mDeliveryMan);
//                r.setStatus("En Route");
//                DeliveryTable.setUptable();
//
//
//
//                }
//             })
//            )
//        );
//
//
//
//
//
//    }
//
//
//
//}
